# ============================================================
# LiveKit Server Config for synkolab-emergency
# ============================================================

port: 7880

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50060
  use_external_ip: true
  enable_loopback_candidate: false

redis:
  address: redis:6379

keys:
  APId76e4b049bcba8e2: 69191190270a64bac6ff9fff06139b9da5666546c3a7082a3d5bcd2b4a8f8d55

logging:
  level: info

room:
  empty_timeout: 300
  max_participants: 50

turn:
  enabled: false
